### ISSUE TITLE
User limit inotify instances reaches or too many open files

### ISSUE THREAD

**Issue by ShawnKion** [kangaroo1122/milo-spring-boot-starter#24]
2024-12-04T13:40:27.193-05:00  INFO 327305 --- [demo-plc4j] [DeviceSchedule-1] c.k.d.d.opcua.milo.utils.KeyStoreLoader  : security temp dir: /tmp/security
2024-12-04T13:40:27.194-05:00  INFO 327305 --- [demo-plc4j] [DeviceSchedule-1] c.k.d.d.opcua.milo.utils.KeyStoreLoader  : Loading KeyStore at /tmp/security/milo-client.pfx
2024-12-04T13:40:27.256-05:00  INFO 327305 --- [demo-plc4j] [DeviceSchedule-1] c.k.d.d.o.milo.pool.MiloConnectFactory   : disconnect opcUaClient milo opc-ua client

建立多个链接的时候会创建太多临时文件，导致服务器无法处理过多文件

**Comment by ShawnKion** [comment]
报错信息如下

java.lang.InterruptedException: User limit of inotify instances reached or too many open files
	at com.kion.dcsplatform.DcsApplicationRunner.lambda$run$0(DcsApplicationRunner.java:63) ~[!/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.1.jar!/:6.1.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

**Comment by kangaroo1122** [comment]
试试最新版本

**Comment by kangaroo1122** [comment]
试试最新 `3.1.2.0.6.15` 版本
